// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface INavLinkFields {
  /** Link Title */
  linkTitle?: string | undefined;

  /** Link Url */
  linkUrl?: string | undefined;

  /** Is external? */
  isExternal?: boolean | undefined;
}

export interface INavLink extends Entry<INavLinkFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "navLink";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPageFields {
  /** Title */
  title: string;

  /** Slug */
  slug: string;

  /** Blocks */
  blocks: IPortfolioProjectsList[];
}

export interface IPage extends Entry<IPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "page";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPortfolioProjectsListFields {
  /** Title */
  title?: string | undefined;

  /** Projects */
  projects?: IPortfolioProjectsListProject[] | undefined;
}

export interface IPortfolioProjectsList
  extends Entry<IPortfolioProjectsListFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "portfolioProjectsList";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPortfolioProjectsListProjectFields {
  /** Title */
  title: string;

  /** Description */
  description: string;

  /** Images */
  images: Asset[];

  /** Video */
  video?: Asset | undefined;

  /** Preview Link */
  previewLink?: string | undefined;

  /** Github Link */
  githubLink?: string | undefined;

  /** Button Text */
  buttonText?: string | undefined;

  /** Technologies */
  technologies: ("tailwindcss" | "next.js" | "sass" | "react.js")[];
}

export interface IPortfolioProjectsListProject
  extends Entry<IPortfolioProjectsListProjectFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "portfolioProjectsListProject";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "navLink"
  | "page"
  | "portfolioProjectsList"
  | "portfolioProjectsListProject";

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
